[Variables]
;NEWSPAPER
City=Geneva
Name=Thibault Robin
;WEATHER
Location=UKXX0085
Unit=M
;TIME
Time=H
;HDD
Drive1=C
Drive1Name=Windows 7 (C:)
Drive2=D
Drive2Name=Data (D:)
;GMAIL
AccountName=
Password=

;-----------------------
; GENERAL
TriptychInterval=30
TriptychDisabled=0

;-----------------------
; MUSIC
MusicPlayerType=2
MusicPlayer=foobar2000

;-----------------------
; FEEDS

Feed1=http://www.google.com/reader/public/atom/user%2F17383761438401921630%2Fbundle%2FTech
Feed2=http://www.google.com/reader/public/atom/user%2F17383761438401921630%2Fbundle%2FNews
Feed3=http://www.google.com/reader/public/atom/user%2F17383761438401921630%2Fbundle%2FArt%20and%20Design
Feed4=http://www.google.com/reader/public/atom/user%2F17383761438401921630%2Fbundle%2FHumor
Feed5=http://www.google.com/reader/public/atom/user%2F17383761438401921630%2Fbundle%2FSoftware%20Development

;-----------------------
;LAUNCHERS

App1=Foobar
App1Path=
App1Label=MUSIC
App2=Thunderbird
App2Path=
App2Label=MAILS
App3=Firefox
App3Path=
App3Label=BROWSER
App4=Photoshop
App4Path=
App4Label=PHOTOSHOP
App5=VlC
App5Path=
App5Label=VIDEO
App6=CCleaner
App6Path=
App6Label=UTILITY
App7=XnView
App7Path=
App7Label=VIEWER
App8=Downloads
App8Path=C:\Users\%USER\Downloads
App8Label=DOWNLOADS
App9=Chrome
App9Path=
App9Label=BROWSER
App10=My Music
App10Path=C:\Users\%USER\Music
App10Label=MUSIC
App11=My Documents
App11Path=C:\Users\%USER\Documents
App11Label=DOCUMENTS
App12=My Videos
App12Path=C:\Users\%USER\Videos
App12Label=VIDEOS
App13=My Pictures
App13Path=C:\Users\%USER\Pictures
App13Label=PICTURES
App14=Word
App14Path=C:\Program Files (x86)\Microsoft Office\Office12\WINWORD.EXE
App14Label=WRITER
